name: deploy to remote

on:
  push:
    branches:
      - lightsail

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - shell: bash
        run: |
          touch .env
          echo "ROOT_PATH=${{ secrets.ROOT_PATH }}" >> .env
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node }}
      - name: gulp build
        uses: actions/setup-node@v2
      - run: yarn install && yarn build
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" --delete ./dist/* bitnami@3.114.21.151:/opt/bitnami/nginx/html/g_fbp/
